### ISSUE TITLE
Error when building server

### ISSUE THREAD

**Issue by h3xstream** [nsec/askgod#3]
I get this error when building the server.
```
$ go build ./cmd/askgod-server
package ./cmd/askgod-server
        cmd\askgod-server\main.go:9:2: use of internal package github.com/nsec/askgod/internal/daemon not allowed
```

**Comment by stgraber** [comment]
That's what happens when you don't build something from within its expected path in the GOPATH.

**Comment by stgraber** [comment]
`go get -d -v -x github.com/nsec/askgod`, then running the build commands from within `~/go/src/github.com/nsec/askgod` should work just fine.
